import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Row, Col, Button } from "react-bootstrap";
import { AiOutlineStar, AiFillStar, AiOutlineDelete } from "react-icons/ai";

export default function Home() {
  const [friends, setFriends] = useState([{ name: "pk", isFavorite: true }]);
  const [searchList, setSearchList] = useState([]);
  const [name, setName] = useState("");

  const toggleFavorite = (index) => {
    let friendsCopy = [...friends];
    let friend = friendsCopy[index];
    friend.isFavorite = !friend.isFavorite;
    friendsCopy[index] = friend;
    setFriends([...friendsCopy]);
  };
  const deleteFriend = (index) => {
    if (window.confirm("Do you really want to remove your friend?")) {
      let friendsCopy = [...friends];
      friendsCopy = friendsCopy.filter((item, i) => i !== index);
      setFriends([...friendsCopy]);
    }
  };
  const addFriend = () => {
    let friendsCopy = [...friends];
    let friend = { name, isFavorite: false };
    friendsCopy.push(friend);
    setFriends([...friendsCopy]);
    setSearchList([]);
    setName("");
  };

  const sortByFav = () => {
    let fav = friends.filter((f) => f.isFavorite);
    let nonFav = friends.filter((f) => f.isFavorite === false);
    let friendsCopy = [...fav, ...nonFav];
    setFriends([...friendsCopy]);
  };

  const search = (value) => {
    if (value === "") {
      setFriends([...friends]);
      setSearchList([]);
    } else {
      let filteredList = friends.filter((f) => f.name.includes(value));

      setSearchList([...filteredList]);
    }
  };

  let list = searchList.length > 0 ? [...searchList] : [...friends];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.box}>
          <Row className={styles.hr}>
            <Col>
              <p className={styles.title}>
                <div>Friends List</div>
              </p>
            </Col>
            <Col>
              <span onClick={() => sortByFav()} className={styles.sortBtn}>
                sort favorites
              </span>
            </Col>
          </Row>
          <Row>
            <Col md={10} lg={10} sm={10} xs={10} className="p-0">
              <input
                className={styles.input}
                type="text"
                onChange={(e) => {
                  setName(e.target.value);
                  search(e.target.value);
                }}
                value={name}
                placeholder="Enter your friends name"
              />
            </Col>{" "}
            <Col md={2} lg={2} sm={2} xs={2}>
              <Row className={styles.flexBox}>
                {/* <Button className={styles.btn}>🔍</Button> */}
                <Button onClick={() => addFriend()} className={styles.btn}>
                  Add
                </Button>
              </Row>
            </Col>
          </Row>
          <div className={styles.scrollbox}>
            {list.length > 0 &&
              list.map((friend, index) => {
                return (
                  <Row key={index} className="justify-content-center">
                    <div className={styles.friendBox}>
                      <Row className="align-items-center">
                        <Col md={9} lg={9} sm={9} xs={9}>
                          <Row>
                            <span className={styles.name}>{friend.name}</span>
                          </Row>
                          <Row>
                            <span className={styles.sub}>is your friend</span>
                          </Row>
                        </Col>
                        <Col md={3} lg={3} sm={3} xs={3}>
                          <Row className="justify-content-flex-end">
                            <Col md={6} lg={6} sm={6} xs={6}>
                              <span
                                onClick={() => toggleFavorite(index)}
                                className={styles.iconBtn}
                              >
                                {friend.isFavorite ? (
                                  <AiFillStar />
                                ) : (
                                  <AiOutlineStar />
                                )}
                              </span>
                            </Col>
                            <Col md={6} lg={6} sm={6} xs={6}>
                              <span
                                onClick={() => deleteFriend(index)}
                                className={styles.iconBtn}
                              >
                                <AiOutlineDelete />
                              </span>
                            </Col>
                          </Row>
                        </Col>
                      </Row>
                    </div>
                  </Row>
                );
              })}
          </div>
        </div>
        <p className={styles.note}>
          {" "}
          Note: Please type name, it will search automatically or you can add
          the entry
        </p>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Created by PK
        </a>
      </footer>
    </div>
  );
}
